-- CreateTable
CREATE TABLE "CompanyData" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "userId" TEXT NOT NULL,
    "COMPANY_searchNip" TEXT,
    "COMPANY_identyfikatorWpisu" TEXT,
    "COMPANY_imie" TEXT,
    "COMPANY_nazwisko" TEXT,
    "COMPANY_nip" TEXT,
    "COMPANY_regon" TEXT,
    "COMPANY_firma" TEXT,
    "COMPANY_adresPocztyElektronicznej" TEXT,
    "COMPANY_adresStronyInternetowej" TEXT,
    "COMPANY_telefon" TEXT,
    "COMPANY_faks" TEXT,
    "COMPANY_adresGlownyTERC" TEXT,
    "COMPANY_adresGlownySIMC" TEXT,
    "COMPANY_adresGlownyULIC" TEXT,
    "COMPANY_adresGlownyMiejscowosc" TEXT,
    "COMPANY_adresGlownyBudynek" TEXT,
    "COMPANY_adresGlownyKodPocztowy" TEXT,
    "COMPANY_adresGlownyPoczta" TEXT,
    "COMPANY_adresGlownyGmina" TEXT,
    "COMPANY_adresGlownyPowiat" TEXT,
    "COMPANY_adresGlownyWojewodztwo" TEXT,
    "COMPANY_adresGlownyOpisNietypowegoMiejscaLokalizacji" TEXT,
    "COMPANY_adresDoreczenTERC" TEXT,
    "COMPANY_adresDoreczenSIMC" TEXT,
    "COMPANY_adresDoreczenULIC" TEXT,
    "COMPANY_adresDoreczenMiejscowosc" TEXT,
    "COMPANY_adresDoreczenBudynek" TEXT,
    "COMPANY_adresDoreczenKodPocztowy" TEXT,
    "COMPANY_adresDoreczenPoczta" TEXT,
    "COMPANY_adresDoreczenGmina" TEXT,
    "COMPANY_adresDoreczenPowiat" TEXT,
    "COMPANY_adresDoreczenWojewodztwo" TEXT,
    "COMPANY_adresDoreczenOpisNietypowegoMiejscaLokalizacji" TEXT,
    "COMPANY_przedsiebiorcaPosiadaObywatelstwaPanstw" TEXT,
    "COMPANY_dataRozpoczeciaDzialalnosci" TEXT,
    "COMPANY_dataZawieszeniaDzialalnosci" TEXT,
    "COMPANY_dataWznowieniaDzialalnosci" TEXT,
    "COMPANY_dataZaprzestaniaDzialalnosci" TEXT,
    "COMPANY_dataWykresleniaWpisuZRejestru" TEXT,
    "COMPANY_malzenskaWspolnoscMajatkowa" TEXT,
    "COMPANY_status" TEXT,
    "COMPANY_kodyPKD" TEXT,
    "COMPANY_spolkiCywilne" TEXT,
    "COMPANY_zakazy" TEXT,
    "COMPANY_informacjeUpadlosc" TEXT,
    "COMPANY_pelnomocnicy" TEXT,
    "COMPANY_uprawnienia" TEXT,
    "COMPANY_rawResponse" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "CompanyData_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "CompanyData_userId_key" ON "CompanyData"("userId");

-- CreateIndex
CREATE INDEX "CompanyData_userId_idx" ON "CompanyData"("userId");
